name: storeapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.3
  connectivity_plus: null
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  file_picker: ^4.2.3
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^8.0.3
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.0.0
  flutter_overlay_loader: ^1.0.3
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  get: ^4.3.7
  hive: null
  hive_flutter: null
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  json_annotation: null
  path_provider: ^2.0.2
  shared_preferences: null
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/images/
